# -*- coding: utf-8 -*-
"""Multiple_Reg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10SrBLzFslS-rZX_Xy2D6zXMee9vHMWzJ
"""

from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

df = pd.DataFrame({'feature1': X[:,0], 'feature2': X[:,1], 'target':y})

df.head()



fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')
fig.show()

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=3)

from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)

print(f"MAE: {mean_absolute_error(y_test,y_pred) }")
print(f"MSE: {mean_squared_error(y_test,y_pred) }")
print(f"R2 score: {r2_score(y_test,y_pred)}")

x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

z_final = reg.predict(final).reshape(10,10)

z = z_final

fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

